#!/bin/sh
# toughwlan docker install script
# author: jamiesun.net@gmail.com
# version: 0.0.2

set -e

install()
{
    pypy -m pip install https://github.com/talkincode/toughlib/archive/master.zip --upgrade --no-deps

    pypy -m pip install https://github.com/talkincode/txportal/archive/master.zip --upgrade --no-deps

    pypy -m pip install https://github.com/talkincode/txradius/archive/master.zip --upgrade --no-deps

    git clone -b master https://github.com/talkincode/toughwlan.git /opt/toughwlan

    ln -s /opt/toughwlan/toughwlan.json /etc/toughwlan.json

    chmod +x /opt/toughwlan/toughctl
}

initserv()
{
    if [ ! -f "/var/toughwlan/data" ];then
        mkdir -p /var/toughwlan/data
    fi

    if [ ! -f "/var/toughwlan/.install" ];then
        pypy /opt/toughwlan/toughctl --initdb
        echo "ok" > /var/toughwlan/.install
        echo "init database ok!"
    fi

    if [ ! -f "/var/toughwlan/toughwlan.json" ];then
        ln -s /opt/toughwlan/toughwlan.json /var/toughwlan/toughwlan.json
    fi

    if [ ! -f "/var/toughwlan/toughshell" ];then
        ln -s /usr/local/bin/toughshell /var/toughwlan/toughshell
    fi

    echo "init service ok!"
}

standalone()
{
    initserv
    pypy /opt/toughwlan/toughctl --standalone
}

admin()
{
    initserv
    pypy /opt/toughwlan/toughctl --admin
}

portal()
{
    initserv
    pypy /opt/toughwlan/toughctl --portal
}

acagent()
{
    initserv
    pypy /opt/toughwlan/toughctl --acagent
}

case "$1" in

  install)
    install
  ;;

  initserv)
    initserv
  ;;

  standalone)
    standalone
  ;;

  admin)
    admin
  ;;

  portal)
    portal
  ;;

  acagent)
    acagent
  ;;

esac

