#!/bin/sh
# toughwlan docker install script
# author: jamiesun.net@gmail.com
# version: 0.0.9

set -e

install()
{
    pypy -m pip install https://github.com/talkincode/toughlib/archive/master.zip --upgrade --no-deps

    pypy -m pip install https://github.com/talkincode/txportal/archive/master.zip --upgrade --no-deps

    pypy -m pip install https://github.com/talkincode/txradius/archive/master.zip --upgrade --no-deps

    git clone -b master https://github.com/talkincode/toughwlan.git /opt/toughwlan

    cp /opt/toughwlan/toughwlan.json /etc/toughwlan.json

    chmod +x /opt/toughwlan/toughctl
    chmod +x /opt/toughwlan/toughrun
}

initserv()
{
    if [ ! -f "/var/toughwlan/data" ];then
        mkdir -p /var/toughwlan/data
    fi

    if [ ! -f "/var/toughwlan/.install" ];then
        pypy /opt/toughwlan/toughctl --initdb
        echo "ok" > /var/toughwlan/.install
        echo "init database ok!"
    fi

    echo "init service ok!"
}

standalone()
{
    initserv
    pypy /opt/toughwlan/toughctl --standalone
}

admin()
{
    initserv
    pypy /opt/toughwlan/toughctl --admin
}

portal()
{
    initserv
    pypy /opt/toughwlan/toughctl --portal
}

acagent()
{
    initserv
    pypy /opt/toughwlan/toughctl --acagent
}

upgrade()
{
    cd /opt/toughwlan
    git pull origin master
}

uplib()
{
    pypy -m pip install https://github.com/talkincode/toughlib/archive/master.zip --upgrade --no-deps
    pypy -m pip install https://github.com/talkincode/txportal/archive/master.zip --upgrade --no-deps
    pypy -m pip install https://github.com/talkincode/txradius/archive/master.zip --upgrade --no-deps
}

case "$1" in

  install)
    install
  ;;

  initserv)
    initserv
  ;;

  standalone)
    standalone
  ;;

  admin)
    admin
  ;;

  portal)
    portal
  ;;

  acagent)
    acagent
  ;;

  upgrade)
    upgrade
  ;;

  uplib)
    uplib
  ;;

esac

