#!/usr/bin/env bash


start()
{
    pypy ./toughctl --portal -c toughportal.conf
}

listen()
{
    pypy ./toughctl --listen -c toughportal.conf
}

ping()
{
    pypy ./toughctl --ping -c toughportal.conf
}

case "$1" in

  start)
    start
  ;;

  listen)
    listen
  ;;

  ping)
    ping
  ;;

esac