#!/usr/bin/env bash


start()
{
    pypy toughctl --admin -c toughadmin.conf
}

initdb()
{
    pypy toughctl --initdb -c toughadmin.conf
}

case "$1" in

  start)
    start
  ;;

  initdb)
    initdb
  ;;

esac