#!/usr/bin/env bash


start()
{
    pypy toughctl --admin -c toughadmin.conf
}

pp()
{
    pypy toughctl --ping portal -c toughadmin.conf
}

pr()
{
    pypy toughctl --ping radius -c toughadmin.conf
}

po()
{
    pypy toughctl --ping oss -c toughadmin.conf
}


initdb()
{
    pypy toughctl --initdb -c toughadmin.conf
}

case "$1" in

  start)
    start
  ;;

  pp)
    pp
  ;;

  pr)
    pr
  ;;

  po)
    po
  ;;

  initdb)
    initdb
  ;;

esac