#!/usr/bin/env bash


cmcc()
{
    pypy toughctl --portal  -vendor cmcc  -c etc/toughac.conf
}

huawei()
{
    pypy toughctl --portal  -vendor huawei  -c etc/toughac.conf
}

webauth()
{
    pypy toughctl --webauth  -c etc/toughac.conf
}


case "$1" in

  cmcc)
    cmcc
  ;;

  huawei)
    huawei
  ;;

  webauth)
    webauth
  ;;

esac