#!/bin/sh
# toughwlan docker install script
# author: jamiesun.net@gmail.com
# version: 0.0.15

set -e

install()
{
    pypy -m pip install https://github.com/talkincode/toughlib/archive/master.zip --upgrade --no-deps

    pypy -m pip install https://github.com/talkincode/txportal/archive/master.zip --upgrade --no-deps

    git clone -b master https://github.com/talkincode/toughwlan.git /opt/toughwlan

    cp /opt/toughwlan/etc/toughwlan.json /etc/toughwlan.json
    cp /opt/toughwlan/etc/supervisord.conf /etc/supervisord.conf

    chmod +x /opt/toughwlan/toughctl
}

initserv()
{
    if [ ! -f "/var/toughwlan/data" ];then
        mkdir -p /var/toughwlan/data
    fi

    if [ ! -f "/var/toughwlan/.install" ];then
        pypy /opt/toughwlan/toughctl --initdb
        echo "ok" > /var/toughwlan/.install
        echo "init database ok!"
    fi
}

standalone()
{
    initserv
    pypy /opt/toughwlan/toughctl --standalone
}

httpd()
{
    initserv
    pypy /opt/toughwlan/toughctl --httpd
}

portald()
{
    initserv
    pypy /opt/toughwlan/toughctl --portald
}

upgrade()
{
    cd /opt/toughwlan
    git fetch origin master
    git reset --hard FETCH_HEAD
    git clean -df
}

uplib()
{
    pypy -m pip install https://github.com/talkincode/toughlib/archive/master.zip --upgrade --no-deps
    pypy -m pip install https://github.com/talkincode/txportal/archive/master.zip --upgrade --no-deps
}

case "$1" in

  install)
    install
  ;;

  initserv)
    initserv
  ;;

  standalone)
    standalone
  ;;

  httpd)
    httpd
  ;;

  portald)
    portald
  ;;


  upgrade)
    upgrade
  ;;

  uplib)
    uplib
  ;;

esac

